[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@motif-contracts/=lib/motif-contracts/src/",
    "@eigenlayer/=lib/motif-contracts/lib/eigen-middleware/lib/eigenlayer-contracts/",
    "@eigenlayer-middleware/=lib/motif-contracts/lib/eigenlayer-middleware/",
]
# A list of ignored solc error codes

# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 200
# Whether or not to use the Yul intermediate representation compilation pipeline
via_ir = false
# Override the Solidity version (this overrides `auto_detect_solc`)
solc_version = '0.8.25'
evm_version = "cancun"


fs_permissions = [
    { access = "read-write", path = "./script/anvil-testnet/" },
    { access = "read-write", path = "./script/anvil-testnet/motif_addresses.json" },
    { access = "read-write", path = "./.env" },
    { access = "read-write", path = "./script/anvil-testnet/cdp-addresses.json" },
]
